// Code generated by tool/generate_workout_types.dart; DO NOT EDIT.

import 'package:aepyornis_app/l10n/app_localizations.dart';

/// Workout type configuration item generated from workout-types.yaml
class WorkoutTypeOption {
  const WorkoutTypeOption({
    required this.value,
    required this.name,
    this.location = false,
    this.distance = false,
    this.repetition = false,
    this.weight = false,
    this.duration = true,
    this.pace = false,
    this.subTypes = const {},
  });

  final String value;
  final String name;
  final bool location;
  final bool distance;
  final bool repetition;
  final bool weight;
  final bool duration;
  final bool pace;
  final Map<String, String> subTypes;
}

/// All workout types defined in workout-types.yaml
const List<WorkoutTypeOption> kWorkoutTypes = [
  WorkoutTypeOption(
    value: 'generic',
    name: 'Generic Activity',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'running',
    name: 'Running',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: true,
    subTypes: {
      'treadmill': 'Treadmill',
      'street': 'Street',
      'trail': 'Trail',
      'track': 'Track',
      'indoor_running': 'Indoor Running',
    },
  ),
  WorkoutTypeOption(
    value: 'cycling',
    name: 'Cycling',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'spin': 'Spin',
      'indoor_cycling': 'Indoor Cycling',
      'road': 'Road',
      'mountain': 'Mountain',
      'downhill': 'Downhill',
      'recumbent': 'Recumbent',
      'cyclocross': 'Cyclocross',
      'hand_cycling': 'Hand Cycling',
      'track_cycling': 'Track Cycling',
      'bmx': 'BMX',
      'gravel_cycling': 'Gravel Cycling',
      'e_bike_mountain': 'E-Bike Mountain',
      'commuting': 'Commuting',
      'mixed_surface': 'Mixed Surface',
      'enduro': 'Enduro',
      'e_bike_enduro': 'E-Bike Enduro',
    },
  ),
  WorkoutTypeOption(
    value: 'transition',
    name: 'Multisport Transition',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'bike_to_run_transition': 'Bike to Run Transition',
      'run_to_bike_transition': 'Run to Bike Transition',
      'swim_to_bike_transition': 'Swim to Bike Transition',
    },
  ),
  WorkoutTypeOption(
    value: 'fitness_equipment',
    name: 'Fitness Equipment',
    location: false,
    distance: false,
    repetition: true,
    weight: true,
    duration: true,
    pace: false,
    subTypes: {
      'indoor_rowing': 'Indoor Rowing',
      'elliptical': 'Elliptical',
      'stair_climbing': 'Stair Climbing',
      'indoor_skiing': 'Indoor Skiing',
      'pilates': 'Pilates',
      'indoor_grinding': 'Indoor Grinding',
    },
  ),
  WorkoutTypeOption(
    value: 'swimming',
    name: 'Swimming',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'lap_swimming': 'Lap Swimming',
      'open_water': 'Open Water',
      'pool_apnea': 'Pool Apnea',
      'dynamic_apnea': 'Dynamic Apnea',
    },
  ),
  WorkoutTypeOption(
    value: 'basketball',
    name: 'Basketball',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'soccer',
    name: 'Soccer',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'tennis',
    name: 'Tennis',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'warm_up': 'Warm Up',
      'match': 'Match',
      'exercise': 'Exercise',
      'challenge': 'Challenge',
      'platform': 'Platform',
    },
  ),
  WorkoutTypeOption(
    value: 'american_football',
    name: 'American Football',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'training',
    name: 'Training',
    location: false,
    distance: false,
    repetition: true,
    weight: true,
    duration: true,
    pace: false,
    subTypes: {
      'flexibility_training': 'Flexibility Training',
      'strength_training': 'Strength Training',
      'cardio_training': 'Cardio Training',
      'yoga': 'Yoga',
      'breathing': 'Breathing',
      'mobility': 'Mobility',
    },
  ),
  WorkoutTypeOption(
    value: 'walking',
    name: 'Walking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'indoor_walking': 'Indoor Walking',
      'casual_walking': 'Casual Walking',
      'speed_walking': 'Speed Walking',
      'indoor_wheelchair_walk': 'Indoor Wheelchair Walk',
    },
  ),
  WorkoutTypeOption(
    value: 'cross_country_skiing',
    name: 'Cross Country Skiing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'skate_skiing': 'Skate Skiing',
    },
  ),
  WorkoutTypeOption(
    value: 'alpine_skiing',
    name: 'Alpine Skiing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'backcountry': 'Backcountry',
      'resort': 'Resort',
    },
  ),
  WorkoutTypeOption(
    value: 'snowboarding',
    name: 'Snowboarding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'backcountry': 'Backcountry',
      'resort': 'Resort',
    },
  ),
  WorkoutTypeOption(
    value: 'rowing',
    name: 'Rowing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'mountaineering',
    name: 'Mountaineering',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'hiking',
    name: 'Hiking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'rucking': 'Rucking',
    },
  ),
  WorkoutTypeOption(
    value: 'multisport',
    name: 'Multisport',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'triathlon': 'Triathlon',
      'duathlon': 'Duathlon',
      'brick': 'Brick',
      'swim_run': 'Swim Run',
      'adventure_race': 'Adventure Race',
      'pool_triathlon': 'Pool Triathlon',
    },
  ),
  WorkoutTypeOption(
    value: 'paddling',
    name: 'Paddling',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'flying',
    name: 'Flying',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'rc_drone': 'RC Drone',
      'wingsuit': 'Wingsuit',
      'fly_canopy': 'Fly Canopy',
      'fly_paraglide': 'Fly Paraglide',
      'fly_paramotor': 'Fly Paramotor',
      'fly_pressurized': 'Fly Pressurized',
      'fly_navigate': 'Fly Navigate',
      'fly_timer': 'Fly Timer',
      'fly_altimeter': 'Fly Altimeter',
      'fly_wx': 'Fly WX',
      'fly_vfr': 'Fly VFR',
      'fly_ifr': 'Fly IFR',
    },
  ),
  WorkoutTypeOption(
    value: 'e_biking',
    name: 'E-Biking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'e_bike_fitness': 'E-Bike Fitness',
    },
  ),
  WorkoutTypeOption(
    value: 'motorcycling',
    name: 'Motorcycling',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'atv': 'ATV',
      'motocross': 'Motocross',
    },
  ),
  WorkoutTypeOption(
    value: 'boating',
    name: 'Boating',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'driving',
    name: 'Driving',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'golf',
    name: 'Golf',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'hang_gliding',
    name: 'Hang Gliding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'horseback_riding',
    name: 'Horseback Riding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'hunting',
    name: 'Hunting',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'hunting_with_dogs': 'Hunting With Dogs',
    },
  ),
  WorkoutTypeOption(
    value: 'fishing',
    name: 'Fishing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'inline_skating',
    name: 'Inline Skating',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'rock_climbing',
    name: 'Rock Climbing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'indoor_climbing': 'Indoor Climbing',
      'bouldering': 'Bouldering',
    },
  ),
  WorkoutTypeOption(
    value: 'sailing',
    name: 'Sailing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'sail_race': 'Sail Race',
      'indoor_grinding': 'Indoor Grinding',
    },
  ),
  WorkoutTypeOption(
    value: 'ice_skating',
    name: 'Ice Skating',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'sky_diving',
    name: 'Sky Diving',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'snowshoeing',
    name: 'Snowshoeing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'snowmobiling',
    name: 'Snowmobiling',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'stand_up_paddleboarding',
    name: 'Stand Up Paddleboarding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'surfing',
    name: 'Surfing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'wakeboarding',
    name: 'Wakeboarding',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'water_skiing',
    name: 'Water Skiing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'kayaking',
    name: 'Kayaking',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'whitewater': 'Whitewater',
    },
  ),
  WorkoutTypeOption(
    value: 'rafting',
    name: 'Rafting',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'whitewater': 'Whitewater',
    },
  ),
  WorkoutTypeOption(
    value: 'windsurfing',
    name: 'Windsurfing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'kitesurfing',
    name: 'Kitesurfing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'tactical',
    name: 'Tactical',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'jumpmaster',
    name: 'Jumpmaster',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'boxing',
    name: 'Boxing',
    location: true,
    distance: false,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'floor_climbing',
    name: 'Floor Climbing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'baseball',
    name: 'Baseball',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'diving',
    name: 'Diving',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'single_gas_diving': 'Single Gas Diving',
      'multi_gas_diving': 'Multi Gas Diving',
      'gauge_diving': 'Gauge Diving',
      'apnea_diving': 'Apnea Diving',
      'apnea_hunting': 'Apnea Hunting',
      'ccr_diving': 'CCR Diving',
    },
  ),
  WorkoutTypeOption(
    value: 'shooting',
    name: 'Sport Shooting',
    location: true,
    distance: true,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'winter_sport',
    name: 'Winter Sport',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'grinding',
    name: 'Grinding',
    location: true,
    distance: false,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'hiit',
    name: 'HIIT',
    location: false,
    distance: false,
    repetition: true,
    weight: true,
    duration: true,
    pace: false,
    subTypes: {
      'hiit_generic': 'High Intensity Interval Training',
      'amrap': 'AMRAP',
      'emom': 'EMOM',
      'tabata': 'Tabata',
    },
  ),
  WorkoutTypeOption(
    value: 'video_gaming',
    name: 'Video Gaming',
    location: false,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'esport': 'Esport',
    },
  ),
  WorkoutTypeOption(
    value: 'racket',
    name: 'Racket Sport',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'pickleball': 'Pickleball',
      'padel': 'Padel',
      'squash': 'Squash',
      'badminton': 'Badminton',
      'racquetball': 'Racquetball',
      'table_tennis': 'Table Tennis',
    },
  ),
  WorkoutTypeOption(
    value: 'wheelchair_push_walk',
    name: 'Wheelchair Push Walk',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'wheelchair_push_run',
    name: 'Wheelchair Push Run',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'meditation',
    name: 'Meditation',
    location: false,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'para_sport',
    name: 'Para Sport',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'disc_golf',
    name: 'Disc Golf',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'team_sport',
    name: 'Team Sport',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'cricket',
    name: 'Cricket',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'rugby',
    name: 'Rugby',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'hockey',
    name: 'Hockey',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'field': 'Field',
      'ice': 'Ice',
    },
  ),
  WorkoutTypeOption(
    value: 'lacrosse',
    name: 'Lacrosse',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'volleyball',
    name: 'Volleyball',
    location: true,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'water_tubing',
    name: 'Water Tubing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'wakesurfing',
    name: 'Wakesurfing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'water_sport',
    name: 'Water Sport',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'archery',
    name: 'Archery',
    location: true,
    distance: true,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'mixed_martial_arts',
    name: 'Mixed Martial Arts',
    location: true,
    distance: false,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'motor_sports',
    name: 'Motor Sports',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {
      'rally': 'Rally',
    },
  ),
  WorkoutTypeOption(
    value: 'snorkeling',
    name: 'Snorkeling',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'dance',
    name: 'Dance',
    location: false,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'jump_rope',
    name: 'Jump Rope',
    location: false,
    distance: false,
    repetition: true,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'mobility',
    name: 'Mobility',
    location: false,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'geocaching',
    name: 'Geocaching',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'canoeing',
    name: 'Canoeing',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'indoor_hand_cycling',
    name: 'Indoor Hand Cycling',
    location: false,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'overland',
    name: 'Overland',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'trolling_motor',
    name: 'Trolling Motor',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'obstacle',
    name: 'Obstacle Course',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'virtual_activity',
    name: 'Virtual Activity',
    location: false,
    distance: false,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'expedition',
    name: 'Expedition',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'ultra',
    name: 'Ultramarathon',
    location: true,
    distance: true,
    repetition: false,
    weight: false,
    duration: true,
    pace: false,
    subTypes: {},
  ),
  WorkoutTypeOption(
    value: 'all',
    name: 'All Sports',
    location: true,
    distance: true,
    repetition: true,
    weight: true,
    duration: true,
    pace: false,
    subTypes: {},
  ),
];

/// Map of workout type keys to WorkoutTypeOption
final Map<String, WorkoutTypeOption> kWorkoutTypeMap = {
  for (final option in kWorkoutTypes) option.value: option,
};

/// Get WorkoutTypeOption by workout type string
WorkoutTypeOption? getWorkoutTypeConfig(String? type) {
  if (type == null) return null;
  return kWorkoutTypeMap[type.toLowerCase().trim()];
}

/// Extension to lookup localized workout type names dynamically
extension WorkoutTypeLocalizations on AppLocalizations {
  String? getWorkoutTypeName(String type) {
    switch (type.toLowerCase().trim()) {
      case 'generic':
        return workoutTypeGeneric;
      case 'running':
        return workoutTypeRunning;
      case 'cycling':
        return workoutTypeCycling;
      case 'transition':
        return workoutTypeTransition;
      case 'fitness_equipment':
        return workoutTypeFitnessEquipment;
      case 'swimming':
        return workoutTypeSwimming;
      case 'basketball':
        return workoutTypeBasketball;
      case 'soccer':
        return workoutTypeSoccer;
      case 'tennis':
        return workoutTypeTennis;
      case 'american_football':
        return workoutTypeAmericanFootball;
      case 'training':
        return workoutTypeTraining;
      case 'walking':
        return workoutTypeWalking;
      case 'cross_country_skiing':
        return workoutTypeCrossCountrySkiing;
      case 'alpine_skiing':
        return workoutTypeAlpineSkiing;
      case 'snowboarding':
        return workoutTypeSnowboarding;
      case 'rowing':
        return workoutTypeRowing;
      case 'mountaineering':
        return workoutTypeMountaineering;
      case 'hiking':
        return workoutTypeHiking;
      case 'multisport':
        return workoutTypeMultisport;
      case 'paddling':
        return workoutTypePaddling;
      case 'flying':
        return workoutTypeFlying;
      case 'e_biking':
        return workoutTypeEBiking;
      case 'motorcycling':
        return workoutTypeMotorcycling;
      case 'boating':
        return workoutTypeBoating;
      case 'driving':
        return workoutTypeDriving;
      case 'golf':
        return workoutTypeGolf;
      case 'hang_gliding':
        return workoutTypeHangGliding;
      case 'horseback_riding':
        return workoutTypeHorsebackRiding;
      case 'hunting':
        return workoutTypeHunting;
      case 'fishing':
        return workoutTypeFishing;
      case 'inline_skating':
        return workoutTypeInlineSkating;
      case 'rock_climbing':
        return workoutTypeRockClimbing;
      case 'sailing':
        return workoutTypeSailing;
      case 'ice_skating':
        return workoutTypeIceSkating;
      case 'sky_diving':
        return workoutTypeSkyDiving;
      case 'snowshoeing':
        return workoutTypeSnowshoeing;
      case 'snowmobiling':
        return workoutTypeSnowmobiling;
      case 'stand_up_paddleboarding':
        return workoutTypeStandUpPaddleboarding;
      case 'surfing':
        return workoutTypeSurfing;
      case 'wakeboarding':
        return workoutTypeWakeboarding;
      case 'water_skiing':
        return workoutTypeWaterSkiing;
      case 'kayaking':
        return workoutTypeKayaking;
      case 'rafting':
        return workoutTypeRafting;
      case 'windsurfing':
        return workoutTypeWindsurfing;
      case 'kitesurfing':
        return workoutTypeKitesurfing;
      case 'tactical':
        return workoutTypeTactical;
      case 'jumpmaster':
        return workoutTypeJumpmaster;
      case 'boxing':
        return workoutTypeBoxing;
      case 'floor_climbing':
        return workoutTypeFloorClimbing;
      case 'baseball':
        return workoutTypeBaseball;
      case 'diving':
        return workoutTypeDiving;
      case 'shooting':
        return workoutTypeShooting;
      case 'winter_sport':
        return workoutTypeWinterSport;
      case 'grinding':
        return workoutTypeGrinding;
      case 'hiit':
        return workoutTypeHiit;
      case 'video_gaming':
        return workoutTypeVideoGaming;
      case 'racket':
        return workoutTypeRacket;
      case 'wheelchair_push_walk':
        return workoutTypeWheelchairPushWalk;
      case 'wheelchair_push_run':
        return workoutTypeWheelchairPushRun;
      case 'meditation':
        return workoutTypeMeditation;
      case 'para_sport':
        return workoutTypeParaSport;
      case 'disc_golf':
        return workoutTypeDiscGolf;
      case 'team_sport':
        return workoutTypeTeamSport;
      case 'cricket':
        return workoutTypeCricket;
      case 'rugby':
        return workoutTypeRugby;
      case 'hockey':
        return workoutTypeHockey;
      case 'lacrosse':
        return workoutTypeLacrosse;
      case 'volleyball':
        return workoutTypeVolleyball;
      case 'water_tubing':
        return workoutTypeWaterTubing;
      case 'wakesurfing':
        return workoutTypeWakesurfing;
      case 'water_sport':
        return workoutTypeWaterSport;
      case 'archery':
        return workoutTypeArchery;
      case 'mixed_martial_arts':
        return workoutTypeMixedMartialArts;
      case 'motor_sports':
        return workoutTypeMotorSports;
      case 'snorkeling':
        return workoutTypeSnorkeling;
      case 'dance':
        return workoutTypeDance;
      case 'jump_rope':
        return workoutTypeJumpRope;
      case 'mobility':
        return workoutTypeMobility;
      case 'geocaching':
        return workoutTypeGeocaching;
      case 'canoeing':
        return workoutTypeCanoeing;
      case 'indoor_hand_cycling':
        return workoutTypeIndoorHandCycling;
      case 'overland':
        return workoutTypeOverland;
      case 'trolling_motor':
        return workoutTypeTrollingMotor;
      case 'obstacle':
        return workoutTypeObstacle;
      case 'virtual_activity':
        return workoutTypeVirtualActivity;
      case 'expedition':
        return workoutTypeExpedition;
      case 'ultra':
        return workoutTypeUltra;
      case 'all':
        return workoutTypeAll;
      default:
        return null;
    }
  }
}
