name: aepyornis_app
description: "Aepyornis - Mobile app to track your workouts"
publish_to: "none"

version: 0.3.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.3
  shared_preferences: ^2.5.2
  intl: any
  go_router: ^17.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  location: ^10.0.2
  flutter_command: ^7.2.2
  result_dart: ^2.0.0
  http: ^1.3.0
  fl_chart: ^1.1.1
  health_connector: ^3.0.0
  fit_tool: ^1.0.5
  http_parser: ^4.1.2
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#fa7a1c"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.png
