name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-apk:
    name: Build & Upload Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.44.8

      - name: Decode keystore and create jks and properties file for signing the app
        shell: bash
        run: |
          echo "$KEYSTORE" | base64 --decode > app/keystore.jks
          echo "storeFile=keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_KEY_PASSWORD }}
        working-directory: ./android

      - name: Build
        run: flutter build apk --release
        shell: bash
        working-directory: ./

      - name: Prepare APK files for Release
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          TAG_NAME="${TAG_NAME:-${{ github.ref_name }}}"
          cp build/app/outputs/flutter-apk/app-release.apk "aepyornis-app-${TAG_NAME}.apk"
          cp build/app/outputs/flutter-apk/app-release.apk "aepyornis-app-release.apk"

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            aepyornis-app-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
